from myprosodynew import MyProsody

b=MyProsody(r"/home/vizzbee/hq/demos/ai/speech/myprosody/myprosody")
p="/home/vizzbee/out.wav"
x=b.myspass(p)
# b.mysptotal(p)
# b.myspgend(p)
# b.myspsyl(p)
# b.mysppaus(p)
# b.myspsr(p)
# b.myspatc(p)
# b.myspst(p)
# b.myspod(p)
# b.myspbala(p)
# b.myspf0mean(p)
# b.myspf0sd(p)
# b.myspf0med(p)
# b.myspf0min(p)
# b.myspf0max(p)
# b.myspf0q25(p)
# b.myspf0q75(p)
# b.mysppron(p)
# b.myprosody(p)
#b.mysplev(p)

print("____Analysis____")
print(x)
print(x['balance'])
print(x['balance'][0])
print(x['excitement'])